name: generate animation

on:
  # Tự động chạy mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *" 
  
  # Cho phép chạy thủ công bất cứ lúc nào
  workflow_dispatch:
  
  # Chạy mỗi khi có thay đổi trên nhánh main
  push:
    branches:
    - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Tạo file svg con rắn từ đóng góp của bạn
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Đẩy file đã tạo lên nhánh 'output'
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#00d2ff&color_dots=#1a1b27,#004c6d,#0084a5,#00bed9,#00d2ff
